### ISSUE TITLE
Feature Request: Prevent multi-join spam

### ISSUE THREAD

**Issue by christianparizeau** [WhiskeyJack96/hellothere#11]
As a user, I sometimes have to disconnect from the server and quickly reconnect. This can cause a rapid double notification to the channel which can be annoying. I would like notifications to the channel for individual users to only occur once in a set interval.

**Comment by WhiskeyJack96** [comment]
Recommend looking at https://pkg.go.dev/time#Since and https://pkg.go.dev/sync#Map to accomplish this.

for the sync map you'll need to type assert when you call "Load"
```golang
sm := sync.Map{}
sm.Store("user1", time.Now)
storeTime := sm.Load("user1").(time.Time)
```
